# Generated by Django 6.0.4 on 2026-05-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Groups_By_Rate",
            new_name="Rate_Group",
        ),
    ]
