# Generated by Django 6.0.4 on 2026-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_groups_by_rate_rate_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
