# Generated by Django 6.0.4 on 2026-05-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_allocation_payment_alter_allocation_record"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rate_Group",
            new_name="GroupRate",
        ),
    ]
