# Generated by Django 6.0.4 on 2026-05-11 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_rate_group_grouprate"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
