# Generated by Django 6.0.4 on 2026-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auditlog_reason_alter_allocation_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="status",
        ),
    ]
