# Generated by Django 6.0.4 on 2026-05-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_auditlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[("u", "UPDATE"), ("d", "DELETE")], default="u", max_length=1
            ),
            preserve_default=False,
        ),
    ]
