# Generated by Django 6.0.4 on 2026-06-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_profile_address_remove_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="company_mobile_numer1",
            new_name="office_number1",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="company_mobile_numer2",
            new_name="office_number2",
        ),
    ]
