# Generated by Django 6.0.6 on 2026-06-08 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_profile_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_parties", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
