# Generated by Django 6.0.6 on 2026-06-10 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_advance_total_amount_alter_advanceusage_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="pcs",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
