# Generated by Django 6.0.4 on 2026-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_otp_rename_is_used_otpverification_used_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtpVerification",
        ),
        migrations.AddField(
            model_name="otp",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
