# Generated by Django 6.0.4 on 2026-06-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_pending_email_alter_userotp_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
        ),
    ]
