# Generated by Django 6.0.6 on 2026-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
