# Generated by Django 6.0.6 on 2026-06-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setting_mode',
            field=models.BooleanField(default=True),
        ),
    ]
