# Generated by Django 6.0.6 on 2026-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setting_reason',
            field=models.BooleanField(default=False),
        ),
    ]
