# Generated by Django 6.0.6 on 2026-07-01 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='tire',
            new_name='tier',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
