# Generated by Django 6.0.6 on 2026-07-02 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_razorpayevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserSubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.usersubscription')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
