# Generated by Django 6.0.6 on 2026-07-04 13:52

import django.contrib.auth.models
import django.db.models.deletion
import user.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_rename_usersubscription_subscription_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("manager", user.managers.CustomUserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="max_assigned_toes",
            new_name="max_assignments_per_customer",
        ),
        migrations.AddField(
            model_name="user",
            name="disabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
