# Generated by Django 6.0.6 on 2026-07-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPendingPlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.JSONField(blank=True, null=True)),
                ('service_id', models.JSONField(blank=True, null=True)),
                ('customer_employee_id', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
