# Generated by Django 6.0.6 on 2026-07-08 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
