# Generated by Django 6.0.6 on 2026-07-18 03:32

import uuid
from django.db import migrations, models


def populate_subscription_public_ids(apps, schema_editor):
    Subscription = apps.get_model("user", "Subscription")

    for subscription in Subscription.objects.filter(public_id__isnull=True).iterator():
        public_id = uuid.uuid4()
        while Subscription.objects.filter(public_id=public_id).exists():
            public_id = uuid.uuid4()

        subscription.public_id = public_id
        subscription.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_subscriptionplan_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='public_id',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_subscription_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
