# Generated by Django 6.0.6 on 2026-07-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_subscriptionplan_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='Plan',
        ),
    ]
