# Generated by Django 6.0.6 on 2026-07-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_rename_subscriptionplan_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_plan',
            new_name='plan',
        ),
    ]
