# Generated by Django 6.0.6 on 2026-07-18 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_settings(apps, schema_editor):
    User = apps.get_model("user", "User")
    Setting = apps.get_model("user", "Setting")

    existing_owner_ids = set(Setting.objects.values_list("owner_id", flat=True))
    missing_owner_ids = (
        User.objects.exclude(id__in=existing_owner_ids).values_list("id", flat=True)
    )

    Setting.objects.bulk_create(
        [
            Setting(owner_id=owner_id, image_required=True, reason_required=True)
            for owner_id in missing_owner_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_subscription_public_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "user_profile" '
                        'DROP COLUMN IF EXISTS "setting_mode";'
                        'ALTER TABLE "user_profile" '
                        'DROP COLUMN IF EXISTS "setting_reason";'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "user_profile" '
                        'ADD COLUMN IF NOT EXISTS "setting_mode" boolean NOT NULL DEFAULT true;'
                        'ALTER TABLE "user_profile" '
                        'ADD COLUMN IF NOT EXISTS "setting_reason" boolean NOT NULL DEFAULT false;'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='profile',
                    name='setting_mode',
                ),
                migrations.RemoveField(
                    model_name='profile',
                    name='setting_reason',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE TABLE IF NOT EXISTS "user_setting" ('
                        '"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, '
                        '"image_required" boolean NOT NULL, '
                        '"reason_required" boolean NOT NULL, '
                        '"owner_id" bigint NOT NULL'
                        ');'
                        'ALTER TABLE "user_setting" '
                        'ADD COLUMN IF NOT EXISTS "image_required" boolean NOT NULL DEFAULT true;'
                        'ALTER TABLE "user_setting" '
                        'ADD COLUMN IF NOT EXISTS "reason_required" boolean NOT NULL DEFAULT true;'
                        'ALTER TABLE "user_setting" '
                        'ADD COLUMN IF NOT EXISTS "owner_id" bigint;'
                        'DELETE FROM "user_setting" WHERE "owner_id" IS NULL;'
                        'ALTER TABLE "user_setting" ALTER COLUMN "image_required" SET NOT NULL;'
                        'ALTER TABLE "user_setting" ALTER COLUMN "reason_required" SET NOT NULL;'
                        'ALTER TABLE "user_setting" ALTER COLUMN "owner_id" SET NOT NULL;'
                        'CREATE UNIQUE INDEX IF NOT EXISTS "user_setting_owner_id_uniq" '
                        'ON "user_setting" ("owner_id");'
                        'DO $$ '
                        'BEGIN '
                        "IF NOT EXISTS ("
                        "SELECT 1 FROM pg_constraint "
                        "WHERE conname = 'user_setting_owner_id_fk'"
                        ") THEN "
                        'ALTER TABLE "user_setting" '
                        'ADD CONSTRAINT "user_setting_owner_id_fk" '
                        'FOREIGN KEY ("owner_id") REFERENCES "user_user" ("id") '
                        'DEFERRABLE INITIALLY DEFERRED;'
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql='DROP TABLE IF EXISTS "user_setting" CASCADE;',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Setting',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('image_required', models.BooleanField(default=True)),
                        ('reason_required', models.BooleanField(default=True)),
                        ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
        migrations.RunPython(
            create_missing_settings,
            migrations.RunPython.noop,
        ),
    ]
