# Generated by Django 6.0.4 on 2026-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_merge_otp_into_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="task",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                ],
                max_length=20,
            ),
        ),
    ]
