# Generated by Django 6.0.6 on 2026-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_usersubscription_razorpay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('semi-annually', 'Semi-Annually'), ('annually', 'Annually')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold')], max_length=10),
        ),
    ]
