# Generated by Django 6.0.6 on 2026-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_subscriptionplan_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
