# Generated by Django 6.0.6 on 2026-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_usersubscriptionhistory_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'cancelled')], default='trial', max_length=10),
        ),
    ]
