# Generated by Django 6.0.6 on 2026-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_assigned_toes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_downloads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_services',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
