# Generated by Django 6.0.6 on 2026-07-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_subscriptionplan_max_assigned_toes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscription',
            new_name='Subscription',
        ),
        migrations.RenameModel(
            old_name='UserSubscriptionHistory',
            new_name='SubscriptionHistory',
        ),
        migrations.RenameField(
            model_name='subscriptionhistory',
            old_name='user_subscription',
            new_name='subscription',
        ),
    ]
