# Generated by Django 6.0.6 on 2026-07-07 14:35

import user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_temporarypendingplanchange'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='previous_razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
