# Generated by Django 6.0.4 on 2026-05-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_parties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_parties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="groups",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.groups",
            ),
        ),
        migrations.AddField(
            model_name="groups_by_rate",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.groups"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.customer"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.payment"
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.payment",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.customer"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.record"
            ),
        ),
        migrations.AddField(
            model_name="advanceusage",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.record"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="record",
            field=models.ManyToManyField(to="core.record"),
        ),
        migrations.AddField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_service",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.service"
            ),
        ),
        migrations.AddField(
            model_name="groups_by_rate",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groups",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="groups_by_rate",
            unique_together={("group", "service")},
        ),
    ]
