# Generated by Django 6.0.4 on 2026-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_record_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
