# Generated by Django 6.0.4 on 2026-05-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_record_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.payment"
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.record"
            ),
        ),
    ]
