# Generated by Django 6.0.4 on 2026-05-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_allocation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="advance",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.payment"
            ),
        ),
    ]
