# Generated by Django 6.0.6 on 2026-06-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_customer_assigned_to_customer_assigned_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
