# Generated by Django 6.0.6 on 2026-06-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_record_discount_alter_request_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amount',
        ),
    ]
