# Generated by Django 6.0.6 on 2026-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auditlog_public_customer_public_groups_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-logged_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
    ]
